export const ADMIN_USERS_LIST_REQUEST = 'ADMIN_USERS_LIST_REQUEST'
export const ADMIN_USERS_LIST_SUCCESS = 'ADMIN_USERS_LIST_SUCCESS'
export const ADMIN_USERS_LIST_FAIL = 'ADMIN_USERS_LIST_FAIL'
export const ADMIN_USERS_LIST_RESET = 'ADMIN_USERS_LIST_RESET'

export const ADMIN_USER_ACTIONS_REQUEST = 'ADMIN_USER_ACTIONS_REQUEST'
export const ADMIN_USER_ACTIONS_SUCCESS = 'ADMIN_USER_ACTIONS_SUCCESS'
export const ADMIN_USER_ACTIONS_FAIL = 'ADMIN_USER_ACTIONS_FAIL'
export const ADMIN_USER_ACTIONS_RESET = 'ADMIN_USER_ACTIONS_RESET'