# Generated by Django 4.0.1 on 2022-02-02 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_alter_like_created_at_alter_post_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='created_at',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateField(verbose_name='Created at'),
        ),
    ]
